"""init

Revision ID: 3ba3fd59d76f
Revises: 
Create Date: 2026-05-03 20:14:14.694200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba3fd59d76f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_favorites_video_id'), 'favorites', ['video_id'], unique=False)
    op.alter_column('scraped_videos', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scraped_videos', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scraped_videos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('scraped_videos', 'download_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('scraped_videos', 'download_progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scraped_videos', 'is_m3u8',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_scraped_status_time', table_name='scraped_videos')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('videos', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'is_scraped',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('videos', 'hls_ready',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_status_created', table_name='videos')
    op.drop_index('ix_videos_status_created', table_name='videos')
    op.drop_index('ix_videos_user_created', table_name='videos')
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.drop_index('idx_user_watched', table_name='watch_history')
    op.create_index(op.f('ix_watch_history_video_id'), 'watch_history', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_history_video_id'), table_name='watch_history')
    op.create_index('idx_user_watched', 'watch_history', ['user_id', 'watched_at'], unique=False)
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.create_index('ix_videos_user_created', 'videos', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_videos_status_created', 'videos', ['status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_status_created', 'videos', ['status', 'created_at'], unique=False)
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('videos', 'hls_ready',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('videos', 'is_scraped',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('videos', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('ix_scraped_status_time', 'scraped_videos', ['status', sa.text('scraped_at DESC')], unique=False)
    op.alter_column('scraped_videos', 'is_m3u8',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scraped_videos', 'download_progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scraped_videos', 'download_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('scraped_videos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('scraped_videos', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scraped_videos', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_favorites_video_id'), table_name='favorites')
    # ### end Alembic commands ###
