"""add_unique_constraints_trgm_indexes_timezone

Revision ID: b0bcfcc3c918
Revises: 5d38eacec367
Create Date: 2026-05-17 16:46:31.284541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0bcfcc3c918'
down_revision: Union[str, None] = '5d38eacec367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('uq_user_video_favorite', 'favorites', ['user_id', 'video_id'])
    op.alter_column('follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('uq_follow', 'follows', ['follower_id', 'followed_id'])
    op.create_index('ix_video_tags_trgm', 'videos', ['tags'], unique=False, postgresql_using='gin', postgresql_ops={'tags': 'gin_trgm_ops'})
    op.create_index('ix_video_title_trgm', 'videos', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.alter_column('watch_history', 'watched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('uq_user_video_watch', 'watch_history', ['user_id', 'video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_video_watch', 'watch_history', type_='unique')
    op.alter_column('watch_history', 'watched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('ix_video_title_trgm', table_name='videos', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_video_tags_trgm', table_name='videos', postgresql_using='gin', postgresql_ops={'tags': 'gin_trgm_ops'})
    op.drop_constraint('uq_follow', 'follows', type_='unique')
    op.alter_column('follows', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint('uq_user_video_favorite', 'favorites', type_='unique')
    op.alter_column('favorites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
