"""auto

Revision ID: d9b69a005d8a
Revises: ed21d1025c43
Create Date: 2026-05-04 14:40:20.908159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b69a005d8a'
down_revision: Union[str, None] = 'ed21d1025c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_like')
    )
    op.create_index(op.f('ix_video_likes_user_id'), 'video_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_likes_video_id'), 'video_likes', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_likes_video_id'), table_name='video_likes')
    op.drop_index(op.f('ix_video_likes_user_id'), table_name='video_likes')
    op.drop_table('video_likes')
    # ### end Alembic commands ###
